spring:
    profiles:
      active: 
        - EN
        - DOG
        - prod
    
guru:
    userName: yamlDBUser
    password: yamlPassword
    jdbcUrl:  yamlURL

---
spring:
    profile:  prof

guru:
    userName: yamlProdDBUser
    password: yamlProdPassword
    jdbcUrl:  yamlProdURL

